## Triangle -> 45 degrees

In [120]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/multiplicity_triangle/EE_triangle_M0.00_Lmult16.00_alpha"
post_path="00_pbc.txt"

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_triangle_all.txt"

CT=3/(np.pi**2*16)

alphas = [1,2,3,4]

pio2=[0,0.02330,0.01496,0.01282,0.01189]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)


data =  np.loadtxt(path,unpack=True)
L=data[0]

cutoffs=np.array(range(40,51))

for a in alphas:
    Ccont=[]
    OoLs=[]
    #L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    S = data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+12], Ss[cutoff:cutoff+12])
    
        #print a, (-popt[1]-pio2[int(a)])/(2.)
        
        #print Ls[cutoff+12]
        Ccont.append((-popt[1]-pio2[int(a)])/(2.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.0))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    abp, dump = curve_fit(extrap_curve, Ls[40:51], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.07767993 -0.04078965  0.82813997]
1 0.0775163018924
[ 0.05037978 -0.02376665  0.85325574]
2 0.0503071355158
[ 0.04340734 -0.37360562  1.90098284]
3 0.0434679363109
[ 0.04063661  2.23241977  9.10082783]
4 0.0406207667455
[104.0, 106.0, 108.0, 110.0, 112.0, 114.0, 116.0, 118.0, 120.0, 122.0, 124.0, 126.0, 128.0]


## Parallelogram -> 135

In [127]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_parallelo45_all.txt"

alphas = [1,2,3,4]

pio2=[0,0.0233,0.0149,0.0127,0.0119]
pio4=[0,0.0777,0.0504,0.0434,0.0406]
thrpio4=[0,0.00503,0.0032,0.00274,0.00253]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(49,52))

data = np.loadtxt(path,unpack=True) 
L = data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S = data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        Ccont.append((-popt[1]/2.-pio4[int(a)]))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[44:48], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:cutoff+12]

plt.show()

[ 0.00156096  0.00389355  0.27076397]
1 0.00490512337093
[ 0.00156096  0.00389355  0.27076397]
2 0.00314914066938
[ 0.00156096  0.00389355  0.27076397]
3 0.00272263577759
[ 0.00156096  0.00389355  0.27076397]
4 0.00237019423122
[104.0, 106.0, 108.0, 110.0]


## Octagon for 135 degrees

In [71]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_octagon_M0.00_Lmult6.00_alpha"
post_path="00_pbc.txt"

CT=3/(np.pi**2*16)

alphas = [1.0,2.0,3.0,4.0]

pio2=[0,0.0233,0.0149,0.0127,0.0119]
pio4=[0,0.0781,0.0505,0.0436,0.0407]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(8,23))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+8], Ss[cutoff:cutoff+8])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        #print Ls[cutoff+6]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    abp, dump = curve_fit(extrap_curve, Ls[8:23],Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.00502733 -0.00559284  1.41308537]
1.0 0.00507642371741
[ 0.0031924  -0.00503829  1.22780691]
2.0 0.0032326157292
[ 0.00267897 -0.00410154  1.04268828]
3.0 0.00268909585766
[ 0.00244174 -0.00368     1.07867481]
4.0 0.0024569275954
[24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0]
