## Triangle -> 45 degrees

In [25]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/multiplicity_triangle/EE_triangle_M0.00_Lmult16.00_alpha"
post_path="00_pbc.txt"

CT=3/(np.pi**2*16)

alphas = [1.0,2.0,3.0,4.0]

pio2=[0,0.0233,0.0149,0.0127,0.0119]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)


cutoff=45

cutoffs=np.array(range(8,34))

for a in alphas:
    Ccont=[]
    OoLs=[]
    L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+14], Ss[cutoff:cutoff+14])
    
        #print a, (-popt[1]-pio2[int(a)])/(2.)
        
        Ccont.append((-popt[1]-pio2[int(a)])/(2.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**0.6369))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    abp, dump = curve_fit(extrap_curve, Ls[8:34], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.07808572 -0.02365753  0.63694296]
1.0 0.0780858866345
[ 0.05051437 -0.01513457  0.71399346]
2.0 0.0506580207023
[ 0.04355997 -0.02044823  1.0872145 ]
3.0 0.0438655357868
[ 0.04070767 -0.05057844  1.53681566]
4.0 0.0410242908533
[68.0, 70.0, 72.0, 74.0, 76.0, 78.0, 80.0, 82.0, 84.0, 86.0, 88.0, 90.0, 92.0, 94.0, 96.0]


## Parallelogram -> 135

In [40]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_parallelo45_M0.00_Lmult8.00_alpha"
post_path="00_pbc.txt"

CT=3/(np.pi**2*16)

alphas = [1.0,2.0,3.0,4.0]

pio2=[0,0.0233,0.0149,0.0127,0.0119]
pio4=[0,0.0781,0.0505,0.0436,0.0407]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(8,29))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+12], Ss[cutoff:cutoff+12])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        Ccont.append((-popt[1]/2.-pio4[int(a)]))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.484))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[8:29], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.00451206  0.00628086  1.48355801]
1.0 0.00451206935206
[ 0.00451206  0.00628086  1.48355801]
2.0 0.00306809919809
[ 0.00451206  0.00628086  1.48355801]
3.0 0.00274279864977
[ 0.00451206  0.00628086  1.48355801]
4.0 0.00265585388822
[60.0, 62.0, 64.0, 66.0, 68.0, 70.0, 72.0, 74.0, 78.0, 80.0, 86.0, 94.0]


## Octagon for 135 degrees

In [71]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_octagon_M0.00_Lmult6.00_alpha"
post_path="00_pbc.txt"

CT=3/(np.pi**2*16)

alphas = [1.0,2.0,3.0,4.0]

pio2=[0,0.0233,0.0149,0.0127,0.0119]
pio4=[0,0.0781,0.0505,0.0436,0.0407]

def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(8,23))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+8], Ss[cutoff:cutoff+8])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        #print Ls[cutoff+6]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    abp, dump = curve_fit(extrap_curve, Ls[8:23],Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.00502733 -0.00559284  1.41308537]
1.0 0.00507642371741
[ 0.0031924  -0.00503829  1.22780691]
2.0 0.0032326157292
[ 0.00267897 -0.00410154  1.04268828]
3.0 0.00268909585766
[ 0.00244174 -0.00368     1.07867481]
4.0 0.0024569275954
[24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0]
