In [7]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm2_M0.00_Lmult6.00_alpha"
post_path="00_pbc.txt"


alphas = [1.0,2.0,3.0,4.0]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(0,2))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+5], Ss[cutoff:cutoff+5])
        #print a, (-popt[1]/4.)
        
        #print Ls[cutoff+5]
        
        Ccont.append((-popt[1]/4.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.4514))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[2:8], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[  7.98626651e-03  -3.36129934e-10   1.03150621e+00]
1.0 0.0113747881857
[  7.98626651e-03  -3.36129934e-10   1.03150621e+00]
2.0 0.00790787199179
[  7.98626651e-03  -3.36129934e-10   1.03150621e+00]
3.0 0.00710577636879
[  7.98626651e-03  -3.36129934e-10   1.03150621e+00]
4.0 0.00673403387737
[6.0, 8.0, 10.0, 12.0, 14.0, 16.0]
