In [21]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm2_M0.00_Lmult8.00_alpha"
post_path="00_pbc.txt"


alphas = [1.0,2.0,3.0,4.0]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(1,6))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+5], Ss[cutoff:cutoff+5])
        #print a, (-popt[1]/8.)
        
        #print Ls[cutoff+5]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**0.5427))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[1:6], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.01044902  0.00306022  0.54271115]
1.0 0.0104490052935
[ 0.01044902  0.00306022  0.54271115]
2.0 0.00688323180718
[ 0.01044902  0.00306022  0.54271115]
3.0 0.00578916184116
[ 0.01044902  0.00306022  0.54271115]
4.0 0.00533329431158
[14.0, 16.0, 18.0, 20.0, 22.0, 24.0]


## tan theta = -2

In [62]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm2_all.txt"

alphas = [1,2,3,4]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(10,13))

data = np.loadtxt(path,unpack=True)
L=data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S=data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/8.)
        
        #print Ls[cutoff+4]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.0))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[5:13], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.00461027  0.00261921  0.31850495]
1 0.0105549851754
[ 0.00461027  0.00261921  0.31850495]
2 0.0067386027728
[ 0.00461027  0.00261921  0.31850495]
3 0.00570736013032
[ 0.00461027  0.00261921  0.31850495]
4 0.00526806114809
[26.0, 28.0, 30.0, 32.0, 34.0]


## tan theta = -1

In [24]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm1_all_mult4.txt"
#path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm1_all.txt"

alphas = [1,2,3,4]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(26,33))
#cutoffs=np.array(range(10,16))

data = np.loadtxt(path,unpack=True)
L=data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S=data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:
        print Ls[cutoff+4]

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/8.)
        
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.0))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    abp, dump = curve_fit(extrap_curve, Ls[26:33], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

plt.show()

62.0
64.0
66.0
68.0
70.0
72.0
74.0
[  5.76659289e-03   1.34172414e-03   1.83089502e+01]
1 0.00510130561013
62.0
64.0
66.0
68.0
70.0
72.0
74.0
[ 0.00318431  0.01998412  0.95783546]
2 0.00320109095288
62.0
64.0
66.0
68.0
70.0
72.0
74.0
[ 0.00263149  0.04820593  1.29622902]
3 0.00256014251398
62.0
64.0
66.0
68.0
70.0
72.0
74.0
[ 0.00233418  0.04467768  1.22125384]
4 0.00226707896684


/usr/local/lib/python2.7/dist-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)


## tan theta = -1/2

In [92]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanmh_all.txt"

alphas = [1,2,3,4]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(16,19))

data = np.loadtxt(path,unpack=True)
L=data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S=data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/8.)
        
        print Ls[cutoff+4]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1.0))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[5:13], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

40.0
42.0
44.0
[ 0.00232957  0.04220749  1.20364283]
1 0.00208408300501
40.0
42.0
44.0
[ 0.00232957  0.04220749  1.20364283]
2 0.00111324021059
40.0
42.0
44.0
[ 0.00232957  0.04220749  1.20364283]
3 0.000488788349986
40.0
42.0
44.0
[ 0.00232957  0.04220749  1.20364283]
4 0.000228035219875
[36.0, 38.0, 40.0, 42.0, 44.0]


## tan theta = 1/2

In [94]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_parallelotanh_all.txt"

alphas = [1,2,3,4]

piotanmh=[0,0.001,0.001,0.001,0.001]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(28,32))

data = np.loadtxt(path,unpack=True) 
L = data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S = data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        #print Ls[cutoff+4]
        Ccont.append((-popt[1]/2.-piotanmh[int(a)]))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[44:48], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:cutoff+12]

plt.show()

[ 0.00232957  0.04220749  1.20364283]
1 0.147067117092
[ 0.00232957  0.04220749  1.20364283]
2 0.0955516772932
[ 0.00232957  0.04220749  1.20364283]
3 0.0824580884804
[ 0.00232957  0.04220749  1.20364283]
4 0.077032319333
[64.0, 66.0, 68.0, 70.0, 72.0]


## tan theta = 2

In [98]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_parallelotan2_all.txt"

alphas = [1,2,3,4]

piotanm2=[0,0.0106,0.00674,0.00571,0.00527]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(29,33))

data = np.loadtxt(path,unpack=True) 
L = data[0]

for a in alphas:
    Ccont=[]
    OoLs=[]
    S = data[a]
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+4], Ss[cutoff:cutoff+4])
        #print a, (-popt[1]/(2.)-pio4[int(a)])
        
        #print Ls[cutoff+4]
        Ccont.append((-popt[1]/2.-piotanm2[int(a)]))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**1))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[44:48], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:cutoff+12]

plt.show()

[ 0.00232957  0.04220749  1.20364283]
1 0.0466256816019
[ 0.00232957  0.04220749  1.20364283]
2 0.0301541819094
[ 0.00232957  0.04220749  1.20364283]
3 0.0259001644133
[ 0.00232957  0.04220749  1.20364283]
4 0.0240607222987
[66.0, 68.0, 70.0, 72.0]
