In [21]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

pre_path="../fermions/square-in-torus/std-prec/data/Renyi1234/EE_band_tanm2_M0.00_Lmult8.00_alpha"
post_path="00_pbc.txt"


alphas = [1.0,2.0,3.0,4.0]


def arealaw(x,a,b,c):
    return a*x + b*np.log(x) + c

def extrap_curve(x, a,b,p):
    return a + b/(x**p)

cutoffs=np.array(range(1,6))

for a in alphas:
    Ccont=[]
    OoLs=[]
    dump, L, S = np.loadtxt(pre_path+str(a)+post_path,unpack=True)
    Ss= [s for (l,s) in sorted(zip(L,S))]
    Ls=sorted(L)
    for cutoff in cutoffs:

        popt, pcov = curve_fit(arealaw, Ls[cutoff:cutoff+5], Ss[cutoff:cutoff+5])
        #print a, (-popt[1]/8.)
        
        #print Ls[cutoff+5]
        
        Ccont.append((-popt[1]/8.))
        #OoLs.append(1./np.log(Ls[cutoff]))
        OoLs.append(1./(Ls[cutoff]**0.5427))
        
        
    p1, p2 = np.polyfit(OoLs,Ccont,1)
    #abp, dump = curve_fit(extrap_curve, Ls[1:6], Ccont)
    print abp
    print a, p2
    plt.plot(OoLs,Ccont,'.-',label=r"$\alpha = $"+str(a))
    plt.plot([0,0.5],[p2,p2+0.5*p1])

print Ls[cutoff:]

plt.show()

[ 0.01044902  0.00306022  0.54271115]
1.0 0.0104490052935
[ 0.01044902  0.00306022  0.54271115]
2.0 0.00688323180718
[ 0.01044902  0.00306022  0.54271115]
3.0 0.00578916184116
[ 0.01044902  0.00306022  0.54271115]
4.0 0.00533329431158
[14.0, 16.0, 18.0, 20.0, 22.0, 24.0]
